apiVersion: v1
kind: Service
metadata:
        name: mysql-svc
        labels:
           app: database
spec:
        ports:
          - port: 3306
            targetPort: 3306
        selector:
            env: dbprod
        clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: mysql-deploy
spec:
        replicas: 1
        selector:
           matchLabels:
                env: dbprod
        template:
           metadata:
              name: dbpod
              labels:   
                env: dbprod
           spec:
              volumes:
                - name: mysql-vol
                  persistentVolumeClaim:
                     claimName: mysql-pvc
              containers:
                - name: dbcont
                  image: mysql:5.7
                  volumeMounts:
                     - name: mysql-vol
                       mountPath: /var/lib/mysql
                  env:
                     - name: MYSQL_ROOT_PASSWORD
                       valueFrom:
                         secretKeyRef:
                           name: myvault
                           key: rootdbpass
                     - name: MYSQL_USER
                       value: himanshu
                     - name: MYSQL_PASSWORD
                       valueFrom:
                         secretKeyRef:
                           name: myvault
                           key: userdbpass
                     - name: MYSQL_DATABASE
                       value: wpdb
        
