apiVersion: v1
kind: Service
metadata:
        name: mysql-svc
        labels:
           app: database
        spec:
           ports:
               - port: 3306
                 targetPort: 3306
           selector:
                 env: dbprod
           clusterIP: None 
